### ISSUE TITLE
How to fix the mongodb

### ISSUE THREAD

**Issue by Sapphire025** [CryptoSingh1337/vidflow-backend#46]
Is mongodb in docker? I connected the dockers image but the error is creating bean with name 'videoRepository' defined in com.saransh.vidflowdata.repository.VideoRepository defined in @EnableMongoRepositories declared on VidFlowWebApplication: Cannot resolve reference to bean 'mongoTemplate' while setting bean property 'mongoOperations'

**Comment by CryptoSingh1337** [comment]
You can use docker as well but before running the application you need to first setup the application.properties file which is under `VidFlowWeb/src/main/resources` folder. Check this out and replace all the fields which are having `${}` with actual values.

**Comment by CryptoSingh1337** [comment]
And please make sure that while running you are passing this as vm arguments `-Dspring.profiles.active=dev`.
See this [https://www.baeldung.com/spring-profiles](https://www.baeldung.com/spring-profiles)
